version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=supersecret
      # Uncomment below when you add PostgreSQL support
      # - DATABASE_URL=postgresql://loguser:logpass@db:5432/logdb
    volumes:
      - ./api/uploads:/app/api/uploads
    restart: unless-stopped
    depends_on: []
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: logdb
      POSTGRES_USER: loguser
      POSTGRES_PASSWORD: logpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    # Remove from "depends_on" in web until you use the db

volumes:
  postgres_data:
