apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-analyzer-upload-pvc
  namespace: log-analyzer
  labels:
    app.kubernetes.io/name: log-analyzer
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-analyzer-logs-pvc
  namespace: log-analyzer
  labels:
    app.kubernetes.io/name: log-analyzer
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
  namespace: log-analyzer
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard