apiVersion: v1
kind: Service
metadata:
  name: log-analyzer-service
  namespace: log-analyzer
  labels:
    app.kubernetes.io/name: log-analyzer
    app.kubernetes.io/component: service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: log-analyzer
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: log-analyzer
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache