apiVersion: v1
kind: Secret
metadata:
  name: {{ include "log-analyzer.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "log-analyzer.labels" . | nindent 4 }}
type: Opaque
data:
  flask-secret-key: {{ .Values.secret.flaskSecretKey | b64enc | quote }}